### ISSUE TITLE
Bug in is_mac_version_or_greater?

### ISSUE THREAD

**Issue by jamesbcd** [moi15moi/FindSystemFontsFilename#1]
Hi moi15moi. Thanks for a really impressive library! I'm running macOS 13.3.1, and to get the library to work on my machine I had to reverse the first comparison in this line:
https://github.com/moi15moi/FindSystemFontsFilename/blob/aee712bb40dfb58a1d05336350c1461bba8c59a3/find_system_fonts_filename/mac_fonts.py#L100

Am I correct in thinking it should be `system_major > minimum_major`?

**Comment by moi15moi** [comment]
You are totally right.
This is an error.

I will fix that in the current week.

Thank you for your issue

**Comment by moi15moi** [comment]
The lastest version, 0.0.4, correct this issue.

Update your FindSystemFontsFilename package: 
```
pip install FindSystemFontsFilename -U
```

**Comment by jamesbcd** [comment]
Thanks!
